version: '3'
services:
  ros-master:
    image: gramaziokohler/abb-a042-driver
    container_name: ros-master
    ports:
      - "11311:11311"
    command:
      - roscore

  ros-bridge:
    image: gramaziokohler/abb-a042-driver
    container_name: ros-bridge
    environment:
      - ROS_HOSTNAME=ros-bridge
      - ROS_MASTER_URI=http://ros-master:11311
    ports:
      - "9090:9090"
    depends_on:
      - ros-master
    command:
      - roslaunch
      - --wait
      - rosbridge_server
      - rosbridge_websocket.launch
      - unregister_timeout:=28800      # This horribly long timeout of 8 hours is to workaround this issue: https://github.com/RobotWebTools/rosbridge_suite/issues/138

  abb-driver:
    image: gramaziokohler/abb-a042-driver
    container_name: abb-driver
    environment:
      - ROS_HOSTNAME=abb-driver
      - ROS_MASTER_URI=http://ros-master:11311
    depends_on:
      - ros-master
    command:
      - roslaunch
      - --wait
      - abb_042_driver
      - bringup.launch
      - robot_ip:=host.docker.internal
