version: '3'
services:
  ros-master:
    image: compasrrc/compas_rrc_driver:v1.1.0
    container_name: ros-master
    environment:
      - ROS_HOSTNAME=ros-master
      - ROS_MASTER_URI=http://ros-master:11311
    ports:
      - "11311:11311"
    command:
      - roscore

  ros-bridge:
    image: compasrrc/compas_rrc_driver:v1.1.0
    container_name: ros-bridge
    environment:
      - ROS_HOSTNAME=ros-bridge
      - ROS_MASTER_URI=http://ros-master:11311
    ports:
      - "9090:9090"
    depends_on:
      - ros-master
    command:
      - roslaunch
      - --wait
      - rosbridge_server
      - rosbridge_websocket.launch
      - unregister_timeout:=28800      # This horribly long timeout of 8 hours is to workaround this issue: https://github.com/RobotWebTools/rosbridge_suite/issues/138

  abb-driver-1:
    image: compasrrc/compas_rrc_driver:v1.1.0
    container_name: abb-driver-1
    environment:
      - ROS_HOSTNAME=abb-driver-1
      - ROS_MASTER_URI=http://ros-master:11311
    depends_on:
      - ros-master
    command:
      - roslaunch
      - --wait
      - compas_rrc_driver
      - bringup.launch
      - robot_ip:=192.168.0.10
      - robot_streaming_port:=30101
      - robot_state_port:=30201
      - namespace:=ctrl1_rob1

  abb-driver-2:
    image: compasrrc/compas_rrc_driver:v1.1.0
    container_name: abb-driver-2
    environment:
      - ROS_HOSTNAME=abb-driver-2
      - ROS_MASTER_URI=http://ros-master:11311
    depends_on:
      - ros-master
    command:
      - roslaunch
      - --wait
      - compas_rrc_driver
      - bringup.launch
      - robot_ip:=192.168.0.20
      - robot_streaming_port:=30101
      - robot_state_port:=30201
      - namespace:=ctrl2_rob1
